- name: Creating Worker2 instances
  hosts: 127.0.0.1
  gather_facts: False

  vars:
      region: us-east-1
      instance_type: t2.micro
      ami: ami-09e67e426f25ce0d7 # Ubuntu20.04
      keypair: n # pem file name

  tasks:

    - name: Create an ec2 instance
      ec2:
         key_name: "{{ keypair }}"
         aws_access_key: "SAVABS"
         aws_secret_key: "CASVAV"
         group: k8  # security group name
         instance_type: "{{ instance_type}}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: "Worker"
         instance_tags:
            Name: "Worker1"
         vpc_subnet_id: "subnet-0f4ae550"
         assign_public_ip: yes
      register: ec2


    - name: Add instance to host group
      add_host:
        hostname:  "{{ item.private_ip }}"
        groups:
        - web
      with_items: "{{ ec2.instances }}"

    - debug:
        msg: Remote IP is "{{ item.public_ip }}"
      with_items: "{{ec2.instances }}"

    - name: Add in inventory file
      lineinfile:
        path: /root/K8_Web_DB/kube-ansible/hosts #/etc/ansible/hosts (by default using custom inventory file in my case)
        insertafter: '^\[workers\]'
        line: "{{ item.public_ip }}"
      with_items: "{{ec2.instances }}"   
    

    - local_action: "wait_for host={{ item.public_ip }} port=22 state=started"
      name: "Wait for EC2 Instance to Spin-up and ready for SSH access"
      with_items: "{{ec2.instances }}"
      
    - name: Refresh Inventory
      meta: refresh_inventory  
      
    - name: SSH Key Export
      shell: cat ~/.ssh/id_rsa.pub | ssh -i /root/K8Auto/n.pem ubuntu@{{ item.public_ip }} "cat >> ~/.ssh/authorized_keys"
      become_user: ubuntu
      delegate_to: localhost
      with_items: "{{ ec2.instances }}"
      

 
      



      
      
      